version: '3.7'

services:
  demo:
    build: .
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    restart: unless-stopped
    ports:
      - 8000:8000
    environment:
      - MT_API_URL=http://localhost:8001/api/v1/translate
      - PYTHONPATH=/app/
      - API_TOKEN=''
      - MAX_REQUEST_LENGTH=5000


